export const MENU = [
  {
    title: "About",
    route: "/about",
  },
  {
    title: "Cost Calculator",
    route: "/cost-calculator",
  },
  {
    title: "FAQ",
    route: "/faq",
  },
  {
    title: "Track A Delivery",
    route: "/track",
  },
];

export const QuickLinks = [
  {
    title: "Home",
    route: "/",
  },
  {
    title: "About",
    route: "/about",
  },
  {
    title: "Contact",
    route: "/contact",
  },
];

// All countries
// length 252

export const countries = [ 
{"label": "Afghanistan", "key": "AF"}, 
{"label": "land Islands", "key": "AX"}, 
{"label": "Albania", "key": "AL"}, 
{"label": "Algeria", "key": "DZ"}, 
{"label": "American Samoa", "key": "AS"}, 
{"label": "AndorrA", "key": "AD"}, 
{"label": "Angola", "key": "AO"}, 
{"label": "Anguilla", "key": "AI"}, 
{"label": "Antarctica", "key": "AQ"}, 
{"label": "Antigua and Barbuda", "key": "AG"}, 
{"label": "Argentina", "key": "AR"}, 
{"label": "Armenia", "key": "AM"}, 
{"label": "Aruba", "key": "AW"}, 
{"label": "Australia", "key": "AU"}, 
{"label": "Austria", "key": "AT"}, 
{"label": "Azerbaijan", "key": "AZ"}, 
{"label": "Bahamas", "key": "BS"}, 
{"label": "Bahrain", "key": "BH"}, 
{"label": "Bangladesh", "key": "BD"}, 
{"label": "Barbados", "key": "BB"}, 
{"label": "Belarus", "key": "BY"}, 
{"label": "Belgium", "key": "BE"}, 
{"label": "Belize", "key": "BZ"}, 
{"label": "Benin", "key": "BJ"}, 
{"label": "Bermuda", "key": "BM"}, 
{"label": "Bhutan", "key": "BT"}, 
{"label": "Bolivia", "key": "BO"}, 
{"label": "Bosnia and Herzegovina", "key": "BA"}, 
{"label": "Botswana", "key": "BW"}, 
{"label": "Bouvet Island", "key": "BV"}, 
{"label": "Brazil", "key": "BR"}, 
{"label": "British Indian Ocean Territory", "key": "IO"}, 
{"label": "Brunei Darussalam", "key": "BN"}, 
{"label": "Bulgaria", "key": "BG"}, 
{"label": "Burkina Faso", "key": "BF"}, 
{"label": "Burundi", "key": "BI"}, 
{"label": "Cambodia", "key": "KH"}, 
{"label": "Cameroon", "key": "CM"}, 
{"label": "Canada", "key": "CA"}, 
{"label": "Cape Verde", "key": "CV"}, 
{"label": "Cayman Islands", "key": "KY"}, 
{"label": "Central African Republic", "key": "CF"}, 
{"label": "Chad", "key": "TD"}, 
{"label": "Chile", "key": "CL"}, 
{"label": "China", "key": "CN"}, 
{"label": "Christmas Island", "key": "CX"}, 
{"label": "Cocos (Keeling) Islands", "key": "CC"}, 
{"label": "Colombia", "key": "CO"}, 
{"label": "Comoros", "key": "KM"}, 
{"label": "Congo", "key": "CG"}, 
{"label": "Congo, The Democratic Republic of the", "key": "CD"}, 
{"label": "Cook Islands", "key": "CK"}, 
{"label": "Costa Rica", "key": "CR"}, 
{"label": "Cote D'Ivoire", "key": "CI"}, 
{"label": "Croatia", "key": "HR"}, 
{"label": "Cuba", "key": "CU"}, 
{"label": "Cyprus", "key": "CY"}, 
{"label": "Czech Republic", "key": "CZ"}, 
{"label": "Denmark", "key": "DK"}, 
{"label": "Djibouti", "key": "DJ"}, 
{"label": "Dominica", "key": "DM"}, 
{"label": "Dominican Republic", "key": "DO"}, 
{"label": "Ecuador", "key": "EC"}, 
{"label": "Egypt", "key": "EG"}, 
{"label": "El Salvador", "key": "SV"}, 
{"label": "Equatorial Guinea", "key": "GQ"}, 
{"label": "Eritrea", "key": "ER"}, 
{"label": "Estonia", "key": "EE"}, 
{"label": "Ethiopia", "key": "ET"}, 
{"label": "Falkland Islands (Malvinas)", "key": "FK"}, 
{"label": "Faroe Islands", "key": "FO"}, 
{"label": "Fiji", "key": "FJ"}, 
{"label": "Finland", "key": "FI"}, 
{"label": "France", "key": "FR"}, 
{"label": "French Guiana", "key": "GF"}, 
{"label": "French Polynesia", "key": "PF"}, 
{"label": "French Southern Territories", "key": "TF"}, 
{"label": "Gabon", "key": "GA"}, 
{"label": "Gambia", "key": "GM"}, 
{"label": "Georgia", "key": "GE"}, 
{"label": "Germany", "key": "DE"}, 
{"label": "Ghana", "key": "GH"}, 
{"label": "Gibraltar", "key": "GI"}, 
{"label": "Greece", "key": "GR"}, 
{"label": "Greenland", "key": "GL"}, 
{"label": "Grenada", "key": "GD"}, 
{"label": "Guadeloupe", "key": "GP"}, 
{"label": "Guam", "key": "GU"}, 
{"label": "Guatemala", "key": "GT"}, 
{"label": "Guernsey", "key": "GG"}, 
{"label": "Guinea", "key": "GN"}, 
{"label": "Guinea-Bissau", "key": "GW"}, 
{"label": "Guyana", "key": "GY"}, 
{"label": "Haiti", "key": "HT"}, 
{"label": "Heard Island and Mcdonald Islands", "key": "HM"}, 
{"label": "Holy See (Vatican City State)", "key": "VA"}, 
{"label": "Honduras", "key": "HN"}, 
{"label": "Hong Kong", "key": "HK"}, 
{"label": "Hungary", "key": "HU"}, 
{"label": "Iceland", "key": "IS"}, 
{"label": "India", "key": "IN"}, 
{"label": "Indonesia", "key": "ID"}, 
{"label": "Iran, Islamic Republic Of", "key": "IR"}, 
{"label": "Iraq", "key": "IQ"}, 
{"label": "Ireland", "key": "IE"}, 
{"label": "Isle of Man", "key": "IM"}, 
{"label": "Israel", "key": "IL"}, 
{"label": "Italy", "key": "IT"}, 
{"label": "Jamaica", "key": "JM"}, 
{"label": "Japan", "key": "JP"}, 
{"label": "Jersey", "key": "JE"}, 
{"label": "Jordan", "key": "JO"}, 
{"label": "Kazakhstan", "key": "KZ"}, 
{"label": "Kenya", "key": "KE"}, 
{"label": "Kiribati", "key": "KI"}, 
{"label": "Korea, Democratic People's Republic of", "key": "KP"}, 
{"label": "Korea, Republic of", "key": "KR"}, 
{"label": "Kuwait", "key": "KW"}, 
{"label": "Kyrgyzstan", "key": "KG"}, 
{"label": "Lao People's Democratic Republic", "key": "LA"}, 
{"label": "Latvia", "key": "LV"}, 
{"label": "Lebanon", "key": "LB"}, 
{"label": "Lesotho", "key": "LS"}, 
{"label": "Liberia", "key": "LR"}, 
{"label": "Libyan Arab Jamahiriya", "key": "LY"}, 
{"label": "Liechtenstein", "key": "LI"}, 
{"label": "Lithuania", "key": "LT"}, 
{"label": "Luxembourg", "key": "LU"}, 
{"label": "Macao", "key": "MO"}, 
{"label": "Macedonia, The Former Yugoslav Republic of", "key": "MK"}, 
{"label": "Madagascar", "key": "MG"}, 
{"label": "Malawi", "key": "MW"}, 
{"label": "Malaysia", "key": "MY"}, 
{"label": "Maldives", "key": "MV"}, 
{"label": "Mali", "key": "ML"}, 
{"label": "Malta", "key": "MT"}, 
{"label": "Marshall Islands", "key": "MH"}, 
{"label": "Martinique", "key": "MQ"}, 
{"label": "Mauritania", "key": "MR"}, 
{"label": "Mauritius", "key": "MU"}, 
{"label": "Mayotte", "key": "YT"}, 
{"label": "Mexico", "key": "MX"}, 
{"label": "Micronesia, Federated States of", "key": "FM"}, 
{"label": "Moldova, Republic of", "key": "MD"}, 
{"label": "Monaco", "key": "MC"}, 
{"label": "Mongolia", "key": "MN"}, 
{"label": "Montenegro", "key": "ME"},
{"label": "Montserrat", "key": "MS"},
{"label": "Morocco", "key": "MA"}, 
{"label": "Mozambique", "key": "MZ"}, 
{"label": "Myanmar", "key": "MM"}, 
{"label": "Namibia", "key": "NA"}, 
{"label": "Nauru", "key": "NR"}, 
{"label": "Nepal", "key": "NP"}, 
{"label": "Netherlands", "key": "NL"}, 
{"label": "Netherlands Antilles", "key": "AN"}, 
{"label": "New Caledonia", "key": "NC"}, 
{"label": "New Zealand", "key": "NZ"}, 
{"label": "Nicaragua", "key": "NI"}, 
{"label": "Niger", "key": "NE"}, 
{"label": "Nigeria", "key": "NG"}, 
{"label": "Niue", "key": "NU"}, 
{"label": "Norfolk Island", "key": "NF"}, 
{"label": "Northern Mariana Islands", "key": "MP"}, 
{"label": "Norway", "key": "NO"}, 
{"label": "Oman", "key": "OM"}, 
{"label": "Pakistan", "key": "PK"}, 
{"label": "Palau", "key": "PW"}, 
{"label": "Palestinian Territory, Occupied", "key": "PS"}, 
{"label": "Panama", "key": "PA"}, 
{"label": "Papua New Guinea", "key": "PG"}, 
{"label": "Paraguay", "key": "PY"}, 
{"label": "Peru", "key": "PE"}, 
{"label": "Philippines", "key": "PH"}, 
{"label": "Pitcairn", "key": "PN"}, 
{"label": "Poland", "key": "PL"}, 
{"label": "Portugal", "key": "PT"}, 
{"label": "Puerto Rico", "key": "PR"}, 
{"label": "Qatar", "key": "QA"}, 
{"label": "Reunion", "key": "RE"}, 
{"label": "Romania", "key": "RO"}, 
{"label": "Russian Federation", "key": "RU"}, 
{"label": "RWANDA", "key": "RW"}, 
{"label": "Saint Helena", "key": "SH"}, 
{"label": "Saint Kitts and Nevis", "key": "KN"}, 
{"label": "Saint Lucia", "key": "LC"}, 
{"label": "Saint Pierre and Miquelon", "key": "PM"}, 
{"label": "Saint Vincent and the Grenadines", "key": "VC"}, 
{"label": "Samoa", "key": "WS"}, 
{"label": "San Marino", "key": "SM"}, 
{"label": "Sao Tome and Principe", "key": "ST"}, 
{"label": "Saudi Arabia", "key": "SA"}, 
{"label": "Senegal", "key": "SN"}, 
{"label": "Serbia", "key": "RS"}, 
{"label": "Seychelles", "key": "SC"}, 
{"label": "Sierra Leone", "key": "SL"}, 
{"label": "Singapore", "key": "SG"}, 
{"label": "Slovakia", "key": "SK"}, 
{"label": "Slovenia", "key": "SI"}, 
{"label": "Solomon Islands", "key": "SB"}, 
{"label": "Somalia", "key": "SO"}, 
{"label": "South Africa", "key": "ZA"}, 
{"label": "South Georgia and the South Sandwich Islands", "key": "GS"}, 
{"label": "Spain", "key": "ES"}, 
{"label": "Sri Lanka", "key": "LK"}, 
{"label": "Sudan", "key": "SD"}, 
{"label": "Surilabel", "key": "SR"}, 
{"label": "Svalbard and Jan Mayen", "key": "SJ"}, 
{"label": "Swaziland", "key": "SZ"}, 
{"label": "Sweden", "key": "SE"}, 
{"label": "Switzerland", "key": "CH"}, 
{"label": "Syrian Arab Republic", "key": "SY"}, 
{"label": "Taiwan, Province of China", "key": "TW"}, 
{"label": "Tajikistan", "key": "TJ"}, 
{"label": "Tanzania, United Republic of", "key": "TZ"}, 
{"label": "Thailand", "key": "TH"}, 
{"label": "Timor-Leste", "key": "TL"}, 
{"label": "Togo", "key": "TG"}, 
{"label": "Tokelau", "key": "TK"}, 
{"label": "Tonga", "key": "TO"}, 
{"label": "Trinidad and Tobago", "key": "TT"}, 
{"label": "Tunisia", "key": "TN"}, 
{"label": "Turkey", "key": "TR"}, 
{"label": "Turkmenistan", "key": "TM"}, 
{"label": "Turks and Caicos Islands", "key": "TC"}, 
{"label": "Tuvalu", "key": "TV"}, 
{"label": "Uganda", "key": "UG"}, 
{"label": "Ukraine", "key": "UA"}, 
{"label": "United Arab Emirates", "key": "AE"}, 
{"label": "United Kingdom", "key": "GB"}, 
{"label": "United States", "key": "US"}, 
{"label": "United States Minor Outlying Islands", "key": "UM"}, 
{"label": "Uruguay", "key": "UY"}, 
{"label": "Uzbekistan", "key": "UZ"}, 
{"label": "Vanuatu", "key": "VU"}, 
{"label": "Venezuela", "key": "VE"}, 
{"label": "Vietnam", "key": "VN"}, 
{"label": "Virgin Islands, British", "key": "VG"}, 
{"label": "Virgin Islands, U.S.", "key": "VI"}, 
{"label": "Wallis and Futuna", "key": "WF"}, 
{"label": "Western Sahara", "key": "EH"}, 
{"label": "Yemen", "key": "YE"}, 
{"label": "Zambia", "key": "ZM"}, 
{"label": "Zimbabwe", "key": "ZW"} 
]

export const faqData: Record<
  string,
  {
    title: string;
    items: {
      question: string;
      answer: string;
    }[];
  }
> = {
  account: {
    title: "Account",
    items: [
      {
        question: "How do I reset my password?",
        answer: "You can reset your password from the login page.",
      },
      {
        question: "Can I update my email address?",
        answer: "Yes, in your account settings.",
      },
      {
        question: "How do I delete my account?",
        answer: "Contact support to delete your account.",
      },
      {
        question: "Can I change my userlabel?",
        answer: "Userlabels are fixed once set.",
      },
      {
        question: "What should I do if I forget my userlabel?",
        answer: "Use the email to login or recover from support.",
      },
      {
        question: "How do I manage notifications?",
        answer: "Visit the notifications tab in account settings.",
      },
      {
        question: "Can I use 2FA for login?",
        answer: "Yes, we support 2FA through authenticator apps.",
      },
    ],
  },
  shipment: {
    title: "Shipment Options",
    items: [
      {
        question: "How do I schedule a shipment?",
        answer: "Use the 'New Shipment' button on your dashboard.",
      },
      {
        question: "Can I cancel a shipment?",
        answer: "Yes, if it hasn’t been picked up yet.",
      },
      {
        question: "Are there size limits for packages?",
        answer: "We allow up to 70kg per package.",
      },
      {
        question: "What are express shipment options?",
        answer: "Express delivers within 1-2 business days.",
      },
      {
        question: "How do I get a quote?",
        answer: "Quotes are generated instantly before confirmation.",
      },
      {
        question: "Are international shipments supported?",
        answer: "Yes, we ship to over 100 countries.",
      },
      {
        question: "Do you offer insurance?",
        answer: "Yes, during shipment creation.",
      },
    ],
  },
  tracking: {
    title: "Tracking my shipment",
    items: [
      {
        question: "How do I track my order?",
        answer: "Use the tracking ID sent to your email.",
      },
      {
        question: "Why is my tracking info not updating?",
        answer: "It may take a few hours after pickup.",
      },
      {
        question: "Can I receive updates by SMS?",
        answer: "Yes, enable this in preferences.",
      },
      {
        question: "What does 'In transit' mean?",
        answer: "It’s on the way to the delivery address.",
      },
      {
        question: "Can I redirect a package?",
        answer: "Yes, via the tracking page if eligible.",
      },
      {
        question: "What if my package is lost?",
        answer: "File a claim through support.",
      },
      {
        question: "How often is tracking updated?",
        answer: "Every time the shipment reaches a hub.",
      },
    ],
  },
  billing: {
    title: "Billing and payment",
    items: [
      {
        question: "What payment methods do you accept?",
        answer: "Credit/debit cards, PayPal, and bank transfers.",
      },
      {
        question: "How do I download invoices?",
        answer: "From the billing section in your profile.",
      },
      {
        question: "Can I split payments?",
        answer: "No, full payment is required before shipment.",
      },
      {
        question: "Why was I charged twice?",
        answer: "Contact support for billing issues.",
      },
      {
        question: "Do you offer business accounts?",
        answer: "Yes, with monthly billing options.",
      },
      {
        question: "How do I update card details?",
        answer: "Edit it from the billing tab.",
      },
      {
        question: "Can I request a refund?",
        answer: "Yes, if the shipment hasn’t started.",
      },
    ],
  },
  bulk: {
    title: "Bulk Shipping",
    items: [
      {
        question: "How do I set up bulk shipping?",
        answer: "Use our bulk upload tool from your dashboard.",
      },
      {
        question: "Is there a discount for bulk?",
        answer: "Yes, tiered discounts apply.",
      },
      {
        question: "What file types are supported?",
        answer: "CSV and Excel files are accepted.",
      },
      {
        question: "Can I save templates?",
        answer: "Yes, to reuse shipment details.",
      },
      {
        question: "How do I label bulk orders?",
        answer: "Labels are generated per item.",
      },
      {
        question: "Is tracking available for bulk?",
        answer: "Yes, individual tracking for each parcel.",
      },
      {
        question: "Can I integrate with APIs?",
        answer: "Yes, our bulk system supports API integration.",
      },
    ],
  },
  pickup: {
    title: "Pickup",
    items: [
      {
        question: "How do I schedule a pickup?",
        answer: "Use the pickup tab on your dashboard.",
      },
      {
        question: "Can I reschedule my pickup?",
        answer: "Yes, anytime before the scheduled time.",
      },
      {
        question: "Are weekend pickups available?",
        answer: "Only in selected cities.",
      },
      {
        question: "Will I get notified before pickup?",
        answer: "Yes, via SMS and email.",
      },
      {
        question: "Can I specify pickup instructions?",
        answer: "Yes, there is a field for that.",
      },
      {
        question: "Is there a fee for pickup?",
        answer: "First 3 pickups per month are free.",
      },
      {
        question: "What if the courier doesn’t arrive?",
        answer: "You can reschedule or contact support.",
      },
    ],
  },
  complaints: {
    title: "Complaints",
    items: [
      {
        question: "How do I file a complaint?",
        answer: "Go to Help Center > Submit Complaint.",
      },
      {
        question: "How long to get a response?",
        answer: "Within 24–48 hours.",
      },
      {
        question: "Can I escalate an issue?",
        answer: "Yes, after 3 business days of no response.",
      },
      {
        question: "What complaints are valid?",
        answer: "Late delivery, damage, billing issues, etc.",
      },
      {
        question: "Do you have live chat support?",
        answer: "Yes, weekdays 9 AM – 6 PM.",
      },
      {
        question: "How to track complaint status?",
        answer: "In your complaint history section.",
      },
      {
        question: "Can I attach files?",
        answer: "Yes, photos or documents can be uploaded.",
      },
    ],
  },
  general: {
    title: "General Enquiries",
    items: [
      {
        question: "Where are you located?",
        answer: "We're a remote-first company with HQ in Lagos.",
      },
      {
        question: "Do you have a mobile app?",
        answer: "Yes, on Android and iOS.",
      },
      {
        question: "Can I refer others?",
        answer: "Yes, through the referral tab.",
      },
      {
        question: "Where can I see company updates?",
        answer: "Follow our blog or newsletter.",
      },
      {
        question: "Is support available 24/7?",
        answer: "Only email is available 24/7; live chat is limited.",
      },
      {
        question: "Do you support NGOs?",
        answer: "Yes, apply through our partnerships form.",
      },
      {
        question: "Is there a help center?",
        answer: "Yes, see our Help page for guides.",
      },
    ],
  },
};

export const statusClasses: Record<string, string> = {
  PENDING: "bg-yellow-100 text-yellow-800",
  CONFIRMED: "bg-blue-100 text-blue-800",
  PICKED_UP: "bg-indigo-100 text-indigo-800",
  IN_TRANSIT: "bg-purple-100 text-purple-800",
  OUT_FOR_DELIVERY: "bg-orange-100 text-orange-800",
  DELIVERED: "bg-green-100 text-green-800",
  CANCELLED: "bg-red-100 text-red-800",
  FAILED_DELIVERY: "bg-gray-200 text-gray-800",
};
