export const MENU = [
  {
    title: "About",
    route: "/about",
  },
  {
    title: "Cost Calculator",
    route: "/cost-calculator",
  },
  {
    title: "FAQ",
    route: "/faq",
  },
  {
    title: "Track A Delivery",
    route: "/track",
  },
];

export const QuickLinks = [
  {
    title: "Home",
    route: "/",
  },
  {
    title: "About",
    route: "/about",
  },
  {
    title: "Contact",
    route: "/contact",
  },
 
];


// All countries
// length 252

export const countries = [
  {label: "Afghanistan",key: "AF"},
  {label: "Åland Islands",key: "AX"},
  {label: "Albania",key: "AL"},
  {label: "Algeria",key: "DZ"},
  {label: "American Samoa",key: "AS"},
  {label: "Andorra",key: "AD"},
  {label: "Angola",key: "AO"},
  {label: "Anguilla",key: "AI"},
  {label: "Antarctica",key: "AQ"},
  {label: "Antigua & Barbuda",key: "AG"},
  {label: "Argentina",key: "AR"},
  {label: "Armenia",key: "AM"},
  {label: "Aruba",key: "AW"},
  {label: "Australia",key: "AU"},
  {label: "Austria",key: "AT"},
  {label: "Azerbaijan",key: "AZ"},
  {label: "Bahamas",key: "BS"},
  {label: "Bahrain",key: "BH"},
  {label: "Bangladesh",key: "BD"},
  {label: "Barbados",key: "BB"},
  {label: "Belarus",key: "BY"},
  {label: "Belgium",key: "BE"},
  {label: "Belize",key: "BZ"},
  {label: "Benin",key: "BJ"},
  {label: "Bermuda",key: "BM"},
  {label: "Bhutan",key: "BT"},
  {label: "Bolivia",key: "BO"},
  {label: "Caribbean Netherlands",key: "BQ"},
  {label: "Bosnia & Herzegovina",key: "BA"},
  {label: "Botswana",key: "BW"},
  {label: "Bouvet Island",key: "BV"},
  {label: "Brazil",key: "BR"},
  {label: "British Indian Ocean Territory",key: "IO"},
  {label: "Brunei",key: "BN"},
  {label: "Bulgaria",key: "BG"},
  {label: "Burkina Faso",key: "BF"},
  {label: "Burundi",key: "BI"},
  {label: "Cambodia",key: "KH"},
  {label: "Cameroon",key: "CM"},
  {label: "Canada",key: "CA"},
  {label: "Cape Verde",key: "CV"},
  {label: "Cayman Islands",key: "KY"},
  {label: "Central African Republic",key: "CF"},
  {label: "Chad",key: "TD"},
  {label: "Chile",key: "CL"},
  {label: "China",key: "CN"},
  {label: "Christmas Island",key: "CX"},
  {label: "Cocos (Keeling) Islands",key: "CC"},
  {label: "Colombia",key: "CO"},
  {label: "Comoros",key: "KM"},
  {label: "Congo - Brazzaville",key: "CG"},
  {label: "Congo - Kinshasa",key: "CD"},
  {label: "Cook Islands",key: "CK"},
  {label: "Costa Rica",key: "CR"},
  {label: "Côte d’Ivoire",key: "CI"},
  {label: "Croatia",key: "HR"},
  {label: "Cuba",key: "CU"},
  {label: "Curaçao",key: "CW"},
  {label: "Cyprus",key: "CY"},
  {label: "Czechia",key: "CZ"},
  {label: "Denmark",key: "DK"},
  {label: "Djibouti",key: "DJ"},
  {label: "Dominica",key: "DM"},
  {label: "Dominican Republic",key: "DO"},
  {label: "Ecuador",key: "EC"},
  {label: "Egypt",key: "EG"},
  {label: "El Salvador",key: "SV"},
  {label: "Equatorial Guinea",key: "GQ"},
  {label: "Eritrea",key: "ER"},
  {label: "Estonia",key: "EE"},
  {label: "Ethiopia",key: "ET"},
  {label: "Falkland Islands (Islas Malvinas)",key: "FK"},
  {label: "Faroe Islands",key: "FO"},
  {label: "Fiji",key: "FJ"},
  {label: "Finland",key: "FI"},
  {label: "France",key: "FR"},
  {label: "French Guiana",key: "GF"},
  {label: "French Polynesia",key: "PF"},
  {label: "French Southern Territories",key: "TF"},
  {label: "Gabon",key: "GA"},
  {label: "Gambia",key: "GM"},
  {label: "Georgia",key: "GE"},
  {label: "Germany",key: "DE"},
  {label: "Ghana",key: "GH"},
  {label: "Gibraltar",key: "GI"},
  {label: "Greece",key: "GR"},
  {label: "Greenland",key: "GL"},
  {label: "Grenada",key: "GD"},
  {label: "Guadeloupe",key: "GP"},
  {label: "Guam",key: "GU"},
  {label: "Guatemala",key: "GT"},
  {label: "Guernsey",key: "GG"},
  {label: "Guinea",key: "GN"},
  {label: "Guinea-Bissau",key: "GW"},
  {label: "Guyana",key: "GY"},
  {label: "Haiti",key: "HT"},
  {label: "Heard & McDonald Islands",key: "HM"},
  {label: "Vatican City",key: "VA"},
  {label: "Honduras",key: "HN"},
  {label: "Hong Kong",key: "HK"},
  {label: "Hungary",key: "HU"},
  {label: "Iceland",key: "IS"},
  {label: "India",key: "IN"},
  {label: "Indonesia",key: "ID"},
  {label: "Iran",key: "IR"},
  {label: "Iraq",key: "IQ"},
  {label: "Ireland",key: "IE"},
  {label: "Isle of Man",key: "IM"},
  {label: "Israel",key: "IL"},
  {label: "Italy",key: "IT"},
  {label: "Jamaica",key: "JM"},
  {label: "Japan",key: "JP"},
  {label: "Jersey",key: "JE"},
  {label: "Jordan",key: "JO"},
  {label: "Kazakhstan",key: "KZ"},
  {label: "Kenya",key: "KE"},
  {label: "Kiribati",key: "KI"},
  {label: "North Korea",key: "KP"},
  {label: "South Korea",key: "KR"},
  {label: "Kosovo",key: "XK"},
  {label: "Kuwait",key: "KW"},
  {label: "Kyrgyzstan",key: "KG"},
  {label: "Laos",key: "LA"},
  {label: "Latvia",key: "LV"},
  {label: "Lebanon",key: "LB"},
  {label: "Lesotho",key: "LS"},
  {label: "Liberia",key: "LR"},
  {label: "Libya",key: "LY"},
  {label: "Liechtenstein",key: "LI"},
  {label: "Lithuania",key: "LT"},
  {label: "Luxembourg",key: "LU"},
  {label: "Macao",key: "MO"},
  {label: "North Macedonia",key: "MK"},
  {label: "Madagascar",key: "MG"},
  {label: "Malawi",key: "MW"},
  {label: "Malaysia",key: "MY"},
  {label: "Maldives",key: "MV"},
  {label: "Mali",key: "ML"},
  {label: "Malta",key: "MT"},
  {label: "Marshall Islands",key: "MH"},
  {label: "Martinique",key: "MQ"},
  {label: "Mauritania",key: "MR"},
  {label: "Mauritius",key: "MU"},
  {label: "Mayotte",key: "YT"},
  {label: "Mexico",key: "MX"},
  {label: "Micronesia",key: "FM"},
  {label: "Moldova",key: "MD"},
  {label: "Monaco",key: "MC"},
  {label: "Mongolia",key: "MN"},
  {label: "Montenegro",key: "ME"},
  {label: "Montserrat",key: "MS"},
  {label: "Morocco",key: "MA"},
  {label: "Mozambique",key: "MZ"},
  {label: "Myanmar (Burma)",key: "MM"},
  {label: "Namibia",key: "NA"},
  {label: "Nauru",key: "NR"},
  {label: "Nepal",key: "NP"},
  {label: "Netherlands",key: "NL"},
  {label: "Curaçao",key: "AN"},
  {label: "New Caledonia",key: "NC"},
  {label: "New Zealand",key: "NZ"},
  {label: "Nicaragua",key: "NI"},
  {label: "Niger",key: "NE"},
  {label: "Nigeria",key: "NG"},
  {label: "Niue",key: "NU"},
  {label: "Norfolk Island",key: "NF"},
  {label: "Northern Mariana Islands",key: "MP"},
  {label: "Norway",key: "NO"},
  {label: "Oman",key: "OM"},
  {label: "Pakistan",key: "PK"},
  {label: "Palau",key: "PW"},
  {label: "Palestine",key: "PS"},
  {label: "Panama",key: "PA"},
  {label: "Papua New Guinea",key: "PG"},
  {label: "Paraguay",key: "PY"},
  {label: "Peru",key: "PE"},
  {label: "Philippines",key: "PH"},
  {label: "Pitcairn Islands",key: "PN"},
  {label: "Poland",key: "PL"},
  {label: "Portugal",key: "PT"},
  {label: "Puerto Rico",key: "PR"},
  {label: "Qatar",key: "QA"},
  {label: "Réunion",key: "RE"},
  {label: "Romania",key: "RO"},
  {label: "Russia",key: "RU"},
  {label: "Rwanda",key: "RW"},
  {label: "St. Barthélemy",key: "BL"},
  {label: "St. Helena",key: "SH"},
  {label: "St. Kitts & Nevis",key: "KN"},
  {label: "St. Lucia",key: "LC"},
  {label: "St. Martin",key: "MF"},
  {label: "St. Pierre & Miquelon",key: "PM"},
  {label: "St. Vincent & Grenadines",key: "VC"},
  {label: "Samoa",key: "WS"},
  {label: "San Marino",key: "SM"},
  {label: "São Tomé & Príncipe",key: "ST"},
  {label: "Saudi Arabia",key: "SA"},
  {label: "Senegal",key: "SN"},
  {label: "Serbia",key: "RS"},
  {label: "Serbia",key: "CS"},
  {label: "Seychelles",key: "SC"},
  {label: "Sierra Leone",key: "SL"},
  {label: "Singapore",key: "SG"},
  {label: "Sint Maarten",key: "SX"},
  {label: "Slovakia",key: "SK"},
  {label: "Slovenia",key: "SI"},
  {label: "Solomon Islands",key: "SB"},
  {label: "Somalia",key: "SO"},
  {label: "South Africa",key: "ZA"},
  {label: "South Georgia & South Sandwich Islands",key: "GS"},
  {label: "South Sudan",key: "SS"},
  {label: "Spain",key: "ES"},
  {label: "Sri Lanka",key: "LK"},
  {label: "Sudan",key: "SD"},
  {label: "Suriname",key: "SR"},
  {label: "Svalbard & Jan Mayen",key: "SJ"},
  {label: "Eswatini",key: "SZ"},
  {label: "Sweden",key: "SE"},
  {label: "Switzerland",key: "CH"},
  {label: "Syria",key: "SY"},
  {label: "Taiwan",key: "TW"},
  {label: "Tajikistan",key: "TJ"},
  {label: "Tanzania",key: "TZ"},
  {label: "Thailand",key: "TH"},
  {label: "Timor-Leste",key: "TL"},
  {label: "Togo",key: "TG"},
  {label: "Tokelau",key: "TK"},
  {label: "Tonga",key: "TO"},
  {label: "Trinidad & Tobago",key: "TT"},
  {label: "Tunisia",key: "TN"},
  {label: "Turkey",key: "TR"},
  {label: "Turkmenistan",key: "TM"},
  {label: "Turks & Caicos Islands",key: "TC"},
  {label: "Tuvalu",key: "TV"},
  {label: "Uganda",key: "UG"},
  {label: "Ukraine",key: "UA"},
  {label: "United Arab Emirates",key: "AE"},
  {label: "United Kingdom",key: "GB"},
  {label: "United States",key: "US"},
  {label: "U.S. Outlying Islands",key: "UM"},
  {label: "Uruguay",key: "UY"},
  {label: "Uzbekistan",key: "UZ"},
  {label: "Vanuatu",key: "VU"},
  {label: "Venezuela",key: "VE"},
  {label: "Vietnam",key: "VN"},
  {label: "British Virgin Islands",key: "VG"},
  {label: "U.S. Virgin Islands",key: "VI"},
  {label: "Wallis & Futuna",key: "WF"},
  {label: "Western Sahara",key: "EH"},
  {label: "Yemen",key: "YE"},
  {label: "Zambia",key: "ZM"},
  {label: "Zimbabwe",key: "ZW"}
];